### ISSUE TITLE
CPI job name is incompatible with multi-CPI

### ISSUE THREAD

**Issue by bgandon** [cloudfoundry/bosh-virtualbox-cpi-release#32]
The job name is currently `shadow-cpi` in this Bosh release, whereas Bosh expects it to be `shadow_cpi` [as per the multi-CPI docs](https://bosh.io/docs/cpi-config/#cpis): “_Director will add `_cpi` suffix to the end of the type when calling the CPI binary_”.

**Comment by bgandon** [comment]
A possible workaround is to create a symbolic link for providing the `shadow_cpi` job as an alias of `shadow-cpi` with such YAML patch:

```yaml
- path: /instance_groups/name=bosh/jobs/name=pre-start-script?
  type: replace
  value:
    name: pre-start-script
    release: os-conf
    properties:
      script: |
        #!/usr/bin/env bash
        set -ex
        cd /var/vcap/jobs
        ln -sfn shadow-cpi shadow_cpi
```

And this requires the `os-conf` release in the deployment manifest. It that may already be there, but can also be added with such YAML patch:
```yaml
- path: /releases/name=os-conf?
  type: replace
  value:
    name: os-conf
    version: ((os_conf_version))
    url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=((os_conf_version))
    sha1: ((os_conf_sha1))
```
